name: "Build Docker Image"

on:
  workflow_dispatch:
    inputs:
      version:
        default: ""
        required: true
        description: ""
        type: string
      java_version:
        default: "21"
        required: false
        description: ""
        type: string
      docker_target:
        default: production
        required: false
        description: ""
        type: string
      platforms:
        default: linux/amd64,linux/arm64
        required: false
        description: ""
        type: string
      image:
        default: "scylladb/ycsb"
        required: false
        description: ""
        type: string
  workflow_call:
    inputs:
      version:
        default: ""
        required: true
        type: string
      java_version:
        default: "21"
        required: true
        description: ""
        type: string
      docker_target:
        default: production
        required: false
        type: string
      platforms:
        default: linux/amd64
        required: false
        type: string
      image:
        default: "scylladb/ycsb"
        required: false
        type: string
    secrets:
      REGISTRY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  build:
    env:
      DOCKER_BUILDKIT: 1
      BUILDX_GIT_INFO: 1
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push API
        uses: useblacksmith/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          pull: true
          platforms: ${{ inputs.platforms }}
          tags: |
            ${{ inputs.image }}:latest
            ${{ inputs.image }}:${{ inputs.version }}
          build-args: |
            INPUT_JAVA_VERSION=${{ inputs.java_version }}
            VERSION=${{ inputs.version }}
